import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta property='og:title' content='Job Posting Page' key='title' />
        <meta
          content='https://nextjs.org/docs/api-reference/next/head'
          property='og:url'
        ></meta>
        <meta
          content='
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem expedita similique rerum, exercitationem id sequi accusantium. Omnis corporis eveniet repudiandae saepe aliquam, sed porro cum placeat consequuntur voluptatum deserunt et.
          '
        ></meta>
        <meta
          content='https://nextjs.org/static/twitter-cards/docs.png'
          property='og:image'
        ></meta>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>HEllo this is our job page</h1>
    </>
  );
}
